#!/bin/bash


set -e

current=`pwd`

cd `dirname $0`

. ./setEnv.sh

# drop existing database
#psql -h ${GREENPLUM_HOST} -U ${GREENPLUM_USER} -d ${GREENPLUM_DB} -c "DROP DATABASE IF EXISTS  ${GREENPLUM_DB}"
createdb -h ${GREENPLUM_HOST} -U ${GREENPLUM_USER} ${GREENPLUM_DB}


# generates data for demo; should take at most 1--2 minutes
psql -h ${GREENPLUM_HOST} -U ${GREENPLUM_USER} -d ${GREENPLUM_DB} -f  ./sample_table.sql


# psql -h ${GREENPLUM_HOST} -U ${GREENPLUM_USER} -d ${GREENPLUM_DB} -c  "CREATE ROLE SPARKROLE SUPERUSER NOCREATEDB NOCREATEROLE CREATEEXTTABLE LOGIN;"
#
# psql -h ${GREENPLUM_HOST} -U ${GREENPLUM_USER} -d ${GREENPLUM_DB} -c  "CREATE USER SPARKUSER WITH PASSWORD 'pivotal' NOSUPERUSER;"
#
# psql -h ${GREENPLUM_HOST} -U ${GREENPLUM_USER} -d ${GREENPLUM_DB} -c  "GRANT SPARKROLE to SPARKUSER;"
#
# psql -h ${GREENPLUM_HOST} -U ${GREENPLUM_USER} -d ${GREENPLUM_DB} -c  "GRANT ALL ON DATABASE ${GREENPLUM_DB}  TO SPARKUSER;"
#
# psql -h ${GREENPLUM_HOST} -U ${GREENPLUM_USER} -d ${GREENPLUM_DB} -c  "GRANT ALL ON TABLE basictable  TO SPARKUSER;"

#CREATE ROLE jsmith WITH SUPERUSER NOCREATEDB NOCREATEROLE CREATEEXTTABLE LOGIN;
#select * from pg_user;

cd $current
